// functions/src/setupTokens.js
//
// Created by Miguel Brown on 2026-05-12.
// Copyright © 2026 Luckey Logic LLC. All rights reserved.
//
// Helpers for the first-admin setup-token flow. The plaintext token is
// generated by `scripts/seed-tenant.js` (one-off) or by `issueSetupToken`
// (admin-callable). Only the SHA-256 hex of the plaintext is ever stored
// in Firestore at `/_setup_tokens/{hash}`. The plaintext exists exactly
// once — at issuance — and is consumed when the recipient claims it.

const crypto = require("crypto");

/**
 * Hashes a setup-token plaintext into its Firestore lookup form.
 *
 * @param {string} plaintext  64-char hex token (or any UTF-8 string).
 * @return {string}           64-char hex SHA-256 of the input.
 */
function hashSetupToken(plaintext) {
  return crypto.createHash("sha256").update(plaintext, "utf8").digest("hex");
}

module.exports = {hashSetupToken};
